#!/usr/bin/env bash
#
# One-shot setup for a PythonAnywhere free ("Beginner") account.
#
# Run it from a PythonAnywhere Bash console:
#
#   git clone https://github.com/Oscar-Opemba/Fashion-Shop.git
#   bash ~/Fashion-Shop/deploy/pythonanywhere_setup.sh
#
# Safe to run again later to pull changes and reinstall — it never overwrites
# an existing .env, so your secrets survive a re-run.

set -euo pipefail

PROJECT_DIR="$HOME/Fashion-Shop"
VENV_DIR="$HOME/.virtualenvs/fashionshop"
# PythonAnywhere sets $USER to your account name, which is also your subdomain.
PA_USER="${USER:-$(whoami)}"
HOST="${PA_USER}.pythonanywhere.com"

echo "==> Deploying as ${PA_USER} -> https://${HOST}"

# --- Python ------------------------------------------------------------------
# Django 6.0 needs Python 3.12+. Pick the newest interpreter that qualifies.
PYTHON=""
for candidate in python3.13 python3.12; do
    if command -v "$candidate" >/dev/null 2>&1; then
        PYTHON="$candidate"
        break
    fi
done

if [ -z "$PYTHON" ]; then
    echo "ERROR: no python3.12+ found. Django 6.0 will not run." >&2
    echo "Fix: Account page -> 'System image' -> switch to the newest one." >&2
    exit 1
fi
echo "==> Using $($PYTHON --version)"

# --- Virtualenv --------------------------------------------------------------
if [ ! -d "$VENV_DIR" ]; then
    echo "==> Creating virtualenv at ${VENV_DIR}"
    "$PYTHON" -m venv "$VENV_DIR"
fi

# shellcheck disable=SC1091
source "$VENV_DIR/bin/activate"

echo "==> Installing dependencies (this takes a few minutes)"
pip install --quiet --upgrade pip
pip install --quiet -r "$PROJECT_DIR/requirements.txt"

cd "$PROJECT_DIR"

# --- Environment file --------------------------------------------------------
# Written once. The M-Pesa credentials are deliberately left blank: they are
# secrets, so they never travel through git. Paste them in afterwards.
if [ ! -f .env ]; then
    echo "==> Writing .env"
    SECRET_KEY="$("$PYTHON" -c 'import secrets; print(secrets.token_urlsafe(50))')"
    CALLBACK_TOKEN="$("$PYTHON" -c 'import secrets; print(secrets.token_urlsafe(24))')"

    cat > .env <<EOF
# Generated by deploy/pythonanywhere_setup.sh for ${HOST}

SECRET_KEY=${SECRET_KEY}
DEBUG=False
ALLOWED_HOSTS=${HOST}
CSRF_TRUSTED_ORIGINS=https://${HOST}

# --- Social login (optional) ---
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
FACEBOOK_CLIENT_ID=
FACEBOOK_CLIENT_SECRET=

# --- M-Pesa Daraja ---
# PythonAnywhere serves this host over https, so it replaces the ngrok tunnel
# as the callback address. Nothing here expires between demos.
MPESA_ENV=sandbox
MPESA_CONSUMER_KEY=
MPESA_CONSUMER_SECRET=
MPESA_SHORTCODE=174379
MPESA_PASSKEY=
MPESA_CALLBACK_BASE_URL=https://${HOST}
MPESA_CALLBACK_TOKEN=${CALLBACK_TOKEN}
MPESA_TRANSACTION_DESC=Online purchase
EOF
    chmod 600 .env
    NEW_ENV=1
else
    echo "==> .env already exists, leaving it alone"
    NEW_ENV=0
fi

# --- Django ------------------------------------------------------------------
echo "==> Collecting static files"
python manage.py collectstatic --noinput >/dev/null

echo "==> Applying migrations"
python manage.py migrate

# --- What the Web tab needs --------------------------------------------------
cat <<EOF

============================================================
Setup done. Now configure the Web tab with these values:

  Source code:     ${PROJECT_DIR}
  Working dir:     ${PROJECT_DIR}
  Virtualenv:      ${VENV_DIR}

  Static files — add BOTH of these mappings:
    URL: /static/    Directory: ${PROJECT_DIR}/staticfiles
    URL: /media/     Directory: ${PROJECT_DIR}/media

  WSGI file: replace its contents with
             ${PROJECT_DIR}/deploy/pythonanywhere_wsgi.py

Then hit the green Reload button.
============================================================
EOF

if [ "$NEW_ENV" = "1" ]; then
    cat <<EOF
Still to do: paste your M-Pesa sandbox credentials into
${PROJECT_DIR}/.env  (MPESA_CONSUMER_KEY, MPESA_CONSUMER_SECRET, MPESA_PASSKEY)
then Reload again.

EOF
fi
