# Generated by Django 6.0.7 on 2026-07-24 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_paid_order_stock_applied_alter_order_phone_and_more'),
        ('shop', '0003_colour_size_product_colours_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Only discount products in these categories. Leave empty to apply to the whole cart.', related_name='coupons', to='shop.category'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(default=1, help_text='Total number of times this coupon can be redeemed.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='coupon',
            name='times_used',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
